### PR TITLE
New structure xl

### PR DESCRIPTION
**Pull request by rjuliaros**
The necessary files to load the parameters of the RBSherpa-XL into ROS and launch it have been added. 

This includes:
   + STL and URDF files of: XL version of the robot, wheels and the steering pieces and the support of the two arms with them. (Probably this part must be splitted into two macros, the support and the arm that must be called two times)
   + ROBOT file: For the moment the additional devices (like imu, gps, ...) are commented.
   + Corrected prefix issue on rbsherpa_std.urdf.xacro
   + Rbsherpa_state.launch: removed inconsistent parameter
   + Arm_control.yaml: all arm controllers have been put on the same file and added ur10_calibration.yaml
   + Rbsherpa_xl_control.yaml: created this file and changed wheel diameter, wheel base and traction.
   + Control/state.launch: Add args to spawn arms and controller
   + Bi arm moveit pkg Rbsherpa_xl_2ur10_moveit_config
   + Removed harcdoded prefix = rbsherpa
   + Removed overwritten args to use subst_value=true
   + Fixed errors id_robot -> robot_id
   + Overwritten arguments removed and added subst_value
   + Removed xmlns:xacro warning
   + Added xacro with moments of inertia

### CODE REVIEW

**Comment by David-rn** [comment]
First of all, great job updating all the files to the new structure. Each group of changes are related to one commit, which is good, and they have descriptive senteces. There is something to be added in order to fix the simulation: 

- `move.launch` file does not exist in the package rbsherpa_navigation

The rest of the PR I think it is correct :smile: great job!

**NOTE:** This only has been tested in simulation. I'm going to create an issue related to test these changes in the real robot as currently we do not have one available

**Comment by rjuliaros** [comment]
I have created an issue related to move_base.launch and move.launch. Since we want the simulation to be as close as possible to the real robot, the next step will be to create a file that starts everything related to navigation and the same for localization.

https://github.com/RobotnikAutomation/rbsherpa_common/issues/2#issue-651489476

**Comment by rjuliaros** [comment]
On the other hand, these changes must be test on the real robot. https://github.com/RobotnikAutomation/rbsherpa_common/issues/3#issue-652116027

**Comment by David-rn** [comment]
Okat, that's nice.  I'll merge this branch into the master one but we have to keep in mind that these changes must be tested on the real robot

**Pull request merged**
